apiVersion: release-notes/v2
kind: feature
area: telemetry

# issue is a list of GitHub issues resolved in this note.
issue:
  - https://github.com/istio/istio/issues/53086

releaseNotes:
- |
  **Added** support customized zipkin collector endpoint.