apiVersion: release-notes/v2
kind: feature
area: installation

releaseNotes:
  - |
    **Removed** support for the `1.20` `compatibilityProfile`. This configured the following settings: `ENABLE_EXTERNAL_NAME_ALIAS`,
    `PERSIST_OLDEST_FIRST_HEURISTIC_FOR_VIRTUAL_SERVICE_HOST_MATCHING`, `VERIFY_CERTIFICATE_AT_CLIENT`, and `ENABLE_AUTO_SNI`.
    All of these flags, with the exception of `ENABLE_AUTO_SNI`, have also been removed from Istio entirely.
