version: '3.8'

services:
  app:
    image: node:18-alpine
    command: sh -c "./wait-for-it.sh mysql:3306 -- yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: francisberi
      MYSQL_DB: todos
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: francisberi
      MYSQL_DATABASE: todos
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
