apiVersion: release-notes/v2
kind: feature
area: traffic-management
# releaseNotes is a markdown listing of any user facing changes. This will appear in the
# release notes.
releaseNotes:
  - |
    **Removed** `istio.io/gateway-name`, please use `gateway.networking.k8s.io/gateway-name` label instead.
