apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shippingservice-fault-injection
  namespace: default
spec:
  hosts:
    - shippingservice.default.svc.cluster.local
  http:
    # Rule for requests from frontend
    - match:
        - sourceLabels:
            app: frontend
      fault:
        delay:
          percentage:
            value: 100
          fixedDelay: 2s # Increased from 0.2s to 2s for more noticeable effect
      route:
        - destination:
            host: shippingservice.default.svc.cluster.local

    # Rule for GetQuote requests from checkoutservice
    - match:
        - sourceLabels:
            app: checkoutservice
          uri:
            regex: ".*/GetQuote"
      fault:
        delay:
          percentage:
            value: 100
          fixedDelay: 2s # Increased from 0.4s to 2s for more noticeable effect
      route:
        - destination:
            host: shippingservice.default.svc.cluster.local

    # Default rule for all other traffic
    - route:
        - destination:
            host: shippingservice.default.svc.cluster.local
