apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shippingservice-fault-injection
  namespace: default
spec:
  hosts:
    - shippingservice.default.svc.cluster.local
  http:
    - match:
        - sourceLabels:
            app: frontend
      fault:
        delay:
          percentage:
            value: 100
          fixedDelay: 0.2s
      route:
        - destination:
            host: shippingservice.default.svc.cluster.local
    - match:
        - sourceLabels:
            app: checkoutservice
          uri:
            regex: ".*/GetQuote"
      fault:
        delay:
          percentage:
            value: 100
          fixedDelay: 0.4s
      route:
        - destination:
            host: shippingservice.default.svc.cluster.local
