apiVersion: release-notes/v2
kind: feature
area: installation

# issue is a list of GitHub issues resolved in this note.
issue:
  - 47998

releaseNotes:
  - |
    **Promoted** Istio dual-stack support to Alpha
